#!/bin/bash
#              `.-/::/-``
#            .-/osssssssso/.               
#           :osyysssssssyyys+-              
#        `.+yyyysssssssssyyyyy+.           
#       `/syyyyyssssssssssyyyyys-`         
#      `/yhyyyyysss++ssosyyyyhhy/`         
#     .ohhhyyyyso++/+oso+syy+shhhho.       
#    .shhhhysoo++//+sss+++yyy+shhhhs.      
#   -yhhhhs+++++++ossso+++yyys+ohhddy:     
#  -yddhhyo+++++osyyss++++yyyyooyhdddy-    
# .yddddhso++osyyyyys+++++yyhhsoshddddy`   
#`odddddhyosyhyyyyyy++++++yhhhyosddddddo   
#.dmdddddhhhhhhhyyyo+++++shhhhhohddddmmh.  
#ddmmdddddhhhhhhhso++++++yhhhhhhdddddmmdy  
#dmmmdddddddhhhyso++++++shhhhhddddddmmmmh  
#-dmmmdddddddhhyso++++oshhhhdddddddmmmmd- 
# .smmmmddddddddhhhhhhhhhdddddddddmmmms. 
#   `+ydmmmdddddddddddddddddddmmmmdy/.     
#      `.:+ooyyddddddddddddyyso+:.`
#
##################################################################################################################
#
# Current project : AntergosGnome
#
# Source 	: 	https://github.com/erikdubois/AntergosGnome
#
##################################################################################################################
#
# Written to be used on 64 bits computers
# Author 	: 	Erik Dubois
# Website 	: 	http://www.erikdubois.be
#
##################################################################################################################
# 
#
# More from Erik Dubois
#
# Aurora Conky
# at http://sourceforge.net/projects/auroraconkytheme/
# Explanation on the use of this theme can be found at 
# http://erikdubois.be/category/linux/aurora-conky/
# 
# Aureola Conky
# Collections of nice conky's with lua syntax
# https://github.com/erikdubois/Aureola
#
# Sardi icons
# Many different styles of icons from colourfull, monochrome, white, circle
# https://sourceforge.net/projects/sardi/
#
# Super Ultra Flat Numix Remix
# Colourfull and playfull icons
# https://github.com/erikdubois/Super-Ultra-Flat-Numix-Remix
#
# Check out the github - many more scripts for automatic installation of Linux Systems.
#
#
#
##################################################################################################################
#
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. AT YOUR OWN RISK.
#
##################################################################################################################
#
#
##################################################################################################################
# If the option -S has been added. It will autoinstall all. Omit if you do not want that.
##################################################################################################################
#
#

1 KEYBOARD

sudo loadkeys be-latin1    in order to have azerty KEYBOARD

change also the following file to make it permanent

sudo nano /etc/vconsole.conf

change your keyboard from "be"  to "be-latin1"

Do the same in gnome - search for keyboard and add Belgian keyboard




	E X T R A


NVIDIA DRIVERS

sudo pacman -S nvidia   and press a few times on TAB - see on nvidia what number
of driver you should install


CNCHI (if during installation cnchi gives you trouble)


Download cnchi from github :

	From the ISO, close Cnchi and run this commands from a terminal:
	sudo pacman -S git
	sudo rm -rf /usr/share/cnchi
	git clone https://github.com/Antergos/cnchi --depth=1
	cd cnchi
	./run﻿


Download cnchi from repo : 

	sudo pacman -Syu
	sudo pacman -S cnchi


